# Generated by Django 3.2.4 on 2021-08-05 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20210730_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_upvotes',
            field=models.ManyToManyField(blank=True, related_name='question_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='QuestionUpvote',
        ),
    ]
